# Copyright 2023 Sylk Technologies
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.8'
services:
  registry:
    image: plm-registry
    # environment:
      # - REGISTRY_CONFIG=.
    networks:
      - plm_network
    depends_on:
      - db
    ports:
      - "7575:7575"
    volumes:
      - ./data/registry/libs:/registry/libs
      - ./data/registry/config.docker.json:/registry/config.json

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: registrydb
    ports:
      - "5432:5432"
    depends_on:
      - envoy
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD","pg_isready -U admin"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - plm_network

  envoy:
    image: envoyproxy/envoy:v1.27-latest
    volumes:
      - ./data/envoy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - plm_network

networks:
  plm_network:
    driver: bridge