version: '3.8'

services:
  registry:
    image: plm-registry
    # environment:
      # - REGISTRY_CONFIG=.
      # - PROTOT_REDIS_HOST="redis://redis/"
    networks:
      - plm_network
    depends_on:
      - db
    ports:
      - "7575:7575"
    volumes:
      - ./data/registry:/registry/plm-registry/libs
      - ./data/registry/config.json:/registry/config.json

  
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: registrydb
    depends_on:
      - envoy
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  envoy:
    image: envoyproxy/envoy:v1.27-latest
    volumes:
      - ./data/envoy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080" # Expose HTTP port
      - "8443:8443" # Expose HTTPS port

networks:
  plm_network:
    driver: bridge