name: CI

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    branches: ["main", "ci-test-branch"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update && rustup component add rustfmt
      - run: cargo fmt -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update && rustup component add clippy
      - run: sudo apt-get update -y && sudo apt-get install -y protobuf-compiler
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all-targets -- -D warnings -D clippy::all
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
      - run: rustup update
      - run: sudo apt-get update -y && sudo apt-get install -y protobuf-compiler
      - uses: Swatinem/rust-cache@v2
      - run: cargo test
        env:
          RUST_BACKTRACE: 1
  
  # deny:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: rustup update
  #     - uses: Swatinem/rust-cache@v2
  #     - run: cargo install cargo-deny || true
  #     - run: cargo deny check

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: cargo install typos-cli || true
      - run: typos

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update
      - run: sudo apt-get update -y && sudo apt-get install -y protobuf-compiler
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --verbose
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker

      - name: Build base
        uses: docker/build-push-action@v2
        with:
          context: ./
          load: true
          tags: |
            sylkbuild/plm:latest
          build-args: |
            SYLK_RELEASE=unstable
