# The way this works is the following:
#
# The create-release job runs purely to initialize the GitHub release itself
# and to output upload_url for the following job.
#
# The build-release job runs only once create-release is finished. It gets the
# release upload URL from create-release job outputs, then builds the release
# executables for each supported platform and attaches them as release assets
# to the previously created release.
#
# The key here is that we create the release only once.
#
# Reference:
# https://eugene-babichenko.github.io/blog/2020/05/09/github-actions-cross-platform-auto-releases/

name: release
on:
  push:
    # Enable when testing release infrastructure on a branch.
    # branches:
    # - ci-test-branch
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    # env:
      # Set to force version number, e.g., when no tag exists.
      # PLM_VERSION: TEST-0.0.0
    outputs:
      rg_version: ${{ env.PLM_VERSION }}
    steps:
      - uses: actions/checkout@v3
      - name: Get the release version from the tag
        shell: bash
        if: env.PLM_VERSION == ''
        run: |
          echo "PLM_VERSION=$GITHUB_REF_NAME" >> $GITHUB_ENV
          echo "version is: ${{ env.PLM_VERSION }}"
      - name: Create GitHub release
        run: gh release create ${{ env.PLM_VERSION }}
        env:
          GH_TOKEN: ${{ secrets.PLM_PAT }}

  build-release:
    name: build-release
    needs: ['create-release']
    runs-on: ${{ matrix.os }}
    env:
      # For some builds, we use cross to test on 32-bit and big-endian
      # systems.
      CARGO: cargo
      # When CARGO is set to CROSS, this is set to `--target matrix.target`.
      TARGET_FLAGS: ""
      # When CARGO is set to CROSS, TARGET_DIR includes matrix.target.
      TARGET_DIR: ./target
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
      # Build static releases with PCRE2.
      PCRE2_SYS_STATIC: 1
    strategy:
      matrix:
        build: [linux, linux-arm, macos, win-msvc, win-gnu, win32-msvc]
        include:
        - build: linux
          os: ubuntu-latest
          rust: nightly
          target: x86_64-unknown-linux-musl
        - build: linux-arm
          os: ubuntu-latest
          rust: nightly
          target: arm-unknown-linux-gnueabihf
        - build: macos
          os: macos-latest
          rust: nightly
          target: x86_64-apple-darwin
        - build: win-msvc
          os: windows-latest
          rust: nightly
          target: x86_64-pc-windows-msvc
        - build: win-gnu
          os: windows-latest
          rust: nightly-x86_64-gnu
          target: x86_64-pc-windows-gnu
        - build: win32-msvc
          os: windows-latest
          rust: nightly
          target: i686-pc-windows-msvc

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make ubuntu-install-packages script executable
      run: chmod +x ci/ubuntu-install-packages.sh

    - name: Install protoc on Windows
      if: matrix.os == 'windows-latest'
      run: |
        choco install protoc

    - name: Install packages (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        ci/ubuntu-install-packages.sh

    - name: Make macos-install-packages script executable
      run: chmod +x ci/macos-install-packages.sh

    - name: Install packages (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        ci/macos-install-packages.sh

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        target: ${{ matrix.target }}

    - name: Use Cross
      shell: bash
      run: |
        cargo install cross
        echo "CARGO=cross" >> $GITHUB_ENV
        echo "TARGET_FLAGS=--target ${{ matrix.target }}" >> $GITHUB_ENV
        echo "TARGET_DIR=./target/${{ matrix.target }}" >> $GITHUB_ENV

    - name: Show command used for Cargo
      run: |
        echo "cargo command is: ${{ env.CARGO }}"
        echo "target flag is: ${{ env.TARGET_FLAGS }}"
        echo "target dir is: ${{ env.TARGET_DIR }}"

    - name: Conditionally set PROTOC based on OS
      run: |
        if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          echo "PROTOC=/usr/bin/protoc" >> $GITHUB_ENV
        elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          echo "PROTOC=/usr/local/bin/protoc" >> $GITHUB_ENV
        elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          echo "PROTOC=/c/ProgramData/Chocolatey/bin/protoc" >> $GITHUB_ENV
        fi
        echo $PROTOC

    - name: Show protoc version
      run: |
        which protoc
        protoc --version
    
    - name: Build release binary
      run: ${{ env.CARGO }} build --verbose --release ${{ env.TARGET_FLAGS }}

    - name: Strip release binary (linux, macos and macos-arm)
      if: matrix.build == 'linux' || matrix.os == 'macos'
      run: strip "plm-cli/target/${{ matrix.target }}/release/plm-cli"

    - name: Strip release binary (arm)
      if: matrix.build == 'linux-arm'
      run: |
        docker run --rm -v \
          "$PWD/target:/target:Z" \
          rustembedded/cross:arm-unknown-linux-gnueabihf \
          arm-linux-gnueabihf-strip \
          plm-cli/target/arm-unknown-linux-gnueabihf/release/plm-cli

    - name: Make cargo-out-dir script executable
      run: chmod +x ci/cargo-out-dir.sh

    - name: Build archive
      shell: bash
      run: |
        outdir="$(ci/cargo-out-dir.sh "${{ env.TARGET_DIR }}")"
        staging="plm-cli-${{ needs.create-release.outputs.plm_version }}-${{ matrix.target }}"
        mkdir -p "$staging"/{complete,doc}

        # cp {README.md,COPYING,UNLICENSE,LICENSE-MIT} "$staging/"
        # cp {CHANGELOG.md,FAQ.md,GUIDE.md} "$staging/doc/"
        # cp "$outdir"/{plm.bash,plm.fish,_plm.ps1} "$staging/complete/"
        # cp complete/_plm "$staging/complete/"

        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          cp "plm-cli/target/${{ matrix.target }}/release/plm-cli.exe" "$staging/"
          7z a "$staging.zip" "$staging"
          certutil -hashfile "$staging.zip" SHA256 > "$staging.zip.sha256"
          echo "ASSET=$staging.zip" >> $GITHUB_ENV
          echo "ASSET_SUM=$staging.zip.sha256" >> $GITHUB_ENV
        else
          # The man page is only generated on Unix systems. ¯\_(ツ)_/¯
          # cp "$outdir"/rg.1 "$staging/doc/"
          cp "plm-cli/target/${{ matrix.target }}/release/plm-cli" "$staging/"
          tar czf "$staging.tar.gz" "$staging"
          shasum -a 256 "$staging.tar.gz" > "$staging.tar.gz.sha256"
          echo "ASSET=$staging.tar.gz" >> $GITHUB_ENV
          echo "ASSET_SUM=$staging.tar.gz.sha256" >> $GITHUB_ENV
        fi

    - name: Upload release archive
      env:
        GH_TOKEN: ${{ secrets.PLM_PAT }}
      run: gh release upload ${{ needs.create-release.outputs.plm_version }} ${{ env.ASSET }} ${{ env.ASSET_SUM }}